// Code generated by contract/generate.py; DO NOT EDIT.
package contract

type VersionRef struct {
	ID       string `json:"id"`
	Revision int    `json:"revision"`
}

type EvidenceRef struct {
	ObjectID  string `json:"object_id"`
	SHA256    string `json:"sha256"`
	Locator   string `json:"locator"`
	OriginID  string `json:"origin_id"`
	DataClass string `json:"data_class"`
}

type ReadRef struct {
	EntityType string `json:"entity_type"`
	ID         string `json:"id"`
	Revision   int    `json:"revision"`
}

type ObjectRef struct {
	SchemaVersion int            `json:"schema_version"`
	ID            string         `json:"id"`
	RelativePath  string         `json:"relative_path"`
	SHA256        string         `json:"sha256"`
	MediaType     string         `json:"media_type"`
	ByteSize      int            `json:"byte_size"`
	DataClass     string         `json:"data_class"`
	CreatedAt     string         `json:"created_at"`
	Extensions    map[string]any `json:"extensions"`
}

type InputEnvelope struct {
	SchemaVersion  int            `json:"schema_version"`
	RequestID      string         `json:"request_id"`
	SessionID      string         `json:"session_id"`
	PrincipalID    string         `json:"principal_id"`
	Origin         string         `json:"origin"`
	ReceivedAt     string         `json:"received_at"`
	Text           string         `json:"text"`
	AttachmentRefs []ObjectRef    `json:"attachment_refs"`
	DataClass      string         `json:"data_class"`
	Extensions     map[string]any `json:"extensions"`
}

type SourceState struct {
	SchemaVersion     int             `json:"schema_version"`
	ID                string          `json:"id"`
	Kind              string          `json:"kind"`
	Revision          int             `json:"revision"`
	Cursor            *map[string]any `json:"cursor"`
	LastSuccessAt     *string         `json:"last_success_at"`
	LastError         *string         `json:"last_error"`
	StaleAfterSeconds int             `json:"stale_after_seconds"`
	Enabled           bool            `json:"enabled"`
	DataClass         string          `json:"data_class"`
	Extensions        map[string]any  `json:"extensions"`
}

type SourceRecord struct {
	SchemaVersion    int               `json:"schema_version"`
	ID               string            `json:"id"`
	SourceID         string            `json:"source_id"`
	ExternalID       string            `json:"external_id"`
	SourceVersion    string            `json:"source_version"`
	ContentHash      string            `json:"content_hash"`
	RawRef           ObjectRef         `json:"raw_ref"`
	ObservedAt       string            `json:"observed_at"`
	SourceUpdatedAt  *string           `json:"source_updated_at"`
	Deleted          bool              `json:"deleted"`
	NormalizedType   string            `json:"normalized_type"`
	Normalized       *FixtureItemValue `json:"normalized"`
	ValidationStatus string            `json:"validation_status"`
	DataClass        string            `json:"data_class"`
	Extensions       map[string]any    `json:"extensions"`
	ValidationError  *string           `json:"validation_error"`
}

type Observation struct {
	SchemaVersion  int             `json:"schema_version"`
	ID             string          `json:"id"`
	SourceRecordID *string         `json:"source_record_id"`
	EntityID       string          `json:"entity_id"`
	Kind           string          `json:"kind"`
	Value          *map[string]any `json:"value"`
	ObservedAt     string          `json:"observed_at"`
	ValidUntil     *string         `json:"valid_until"`
	Certainty      string          `json:"certainty"`
	Evidence       []EvidenceRef   `json:"evidence"`
	DataClass      string          `json:"data_class"`
	Extensions     map[string]any  `json:"extensions"`
}

type Item struct {
	SchemaVersion int            `json:"schema_version"`
	ID            string         `json:"id"`
	Revision      int            `json:"revision"`
	Domain        string         `json:"domain"`
	Kind          string         `json:"kind"`
	Title         string         `json:"title"`
	Status        string         `json:"status"`
	Priority      int            `json:"priority"`
	DueAt         *string        `json:"due_at"`
	Timezone      string         `json:"timezone"`
	TimeState     string         `json:"time_state"`
	ParentID      *string        `json:"parent_id"`
	DependencyIDs []string       `json:"dependency_ids"`
	Evidence      []EvidenceRef  `json:"evidence"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
	Extensions    map[string]any `json:"extensions"`
}

type WorldUpdateProposal struct {
	SchemaVersion    int             `json:"schema_version"`
	ID               string          `json:"id"`
	RequestID        string          `json:"request_id"`
	EntityID         string          `json:"entity_id"`
	Predicate        string          `json:"predicate"`
	Operation        string          `json:"operation"`
	FactID           string          `json:"fact_id"`
	ExpectedRevision int             `json:"expected_revision"`
	Value            *map[string]any `json:"value"`
	Evidence         []EvidenceRef   `json:"evidence"`
	Basis            string          `json:"basis"`
	PolicyRevision   int             `json:"policy_revision"`
	Reason           string          `json:"reason"`
	Extensions       map[string]any  `json:"extensions"`
}

type WorldFact struct {
	SchemaVersion  int             `json:"schema_version"`
	ID             string          `json:"id"`
	Revision       int             `json:"revision"`
	EntityID       string          `json:"entity_id"`
	Predicate      string          `json:"predicate"`
	Value          *map[string]any `json:"value"`
	Status         string          `json:"status"`
	ValidFrom      *string         `json:"valid_from"`
	ValidUntil     *string         `json:"valid_until"`
	Evidence       []EvidenceRef   `json:"evidence"`
	ProposalID     string          `json:"proposal_id"`
	AcceptanceRule string          `json:"acceptance_rule"`
	PolicyRevision int             `json:"policy_revision"`
	ConflictGroup  *string         `json:"conflict_group"`
	Supersedes     *VersionRef     `json:"supersedes"`
	CreatedAt      string          `json:"created_at"`
	Extensions     map[string]any  `json:"extensions"`
}

type WorldModelInput struct {
	SchemaVersion         int            `json:"schema_version"`
	SnapshotSeq           int            `json:"snapshot_seq"`
	AsOf                  string         `json:"as_of"`
	Facts                 []WorldFact    `json:"facts"`
	UnresolvedConflictIDs []string       `json:"unresolved_conflict_ids"`
	OmittedCount          int            `json:"omitted_count"`
	MissingReasons        []string       `json:"missing_reasons"`
	Extensions            map[string]any `json:"extensions"`
}

type LiveWorldStateInput struct {
	SchemaVersion  int              `json:"schema_version"`
	SnapshotSeq    int              `json:"snapshot_seq"`
	AsOf           string           `json:"as_of"`
	Items          []Item           `json:"items"`
	TaskRefs       []VersionRef     `json:"task_refs"`
	Observations   []Observation    `json:"observations"`
	SourceStates   []SourceState    `json:"source_states"`
	Freshness      []map[string]any `json:"freshness"`
	OmittedCount   int              `json:"omitted_count"`
	MissingReasons []string         `json:"missing_reasons"`
	Extensions     map[string]any   `json:"extensions"`
}

type ConsciousnessStateInput struct {
	SchemaVersion      int                 `json:"schema_version"`
	Slot               int                 `json:"slot"`
	SnapshotSeq        int                 `json:"snapshot_seq"`
	AsOf               string              `json:"as_of"`
	ChangesFromSeq     int                 `json:"changes_from_seq"`
	PreviousSnapshotID *string             `json:"previous_snapshot_id"`
	World              WorldModelInput     `json:"world"`
	Live               LiveWorldStateInput `json:"live"`
	OpenTaskRefs       []VersionRef        `json:"open_task_refs"`
	RecentChanges      []ChangeEvent       `json:"recent_changes"`
	MissedSlots        int                 `json:"missed_slots"`
	Extensions         map[string]any      `json:"extensions"`
	PreviousSnapshot   *ConsciousnessState `json:"previous_snapshot"`
	Tasks              []Task              `json:"tasks"`
}

type FocusEntry struct {
	Entity   ReadRef       `json:"entity"`
	Reason   string        `json:"reason"`
	Evidence []EvidenceRef `json:"evidence"`
}

type ConsciousnessState struct {
	SchemaVersion      int            `json:"schema_version"`
	ID                 string         `json:"id"`
	Revision           int            `json:"revision"`
	Slot               int            `json:"slot"`
	SnapshotSeq        int            `json:"snapshot_seq"`
	PreviousSnapshotID *string        `json:"previous_snapshot_id"`
	InputHash          string         `json:"input_hash"`
	CreatedAt          string         `json:"created_at"`
	FocalGoals         []FocusEntry   `json:"focal_goals"`
	PriorityItems      []FocusEntry   `json:"priority_items"`
	OpenLoops          []FocusEntry   `json:"open_loops"`
	ImportantChanges   []FocusEntry   `json:"important_changes"`
	Uncertainties      []string       `json:"uncertainties"`
	BriefSummary       string         `json:"brief_summary"`
	MissedSlots        int            `json:"missed_slots"`
	Extensions         map[string]any `json:"extensions"`
}

type ConversationEvent struct {
	SchemaVersion int            `json:"schema_version"`
	ID            string         `json:"id"`
	SessionID     string         `json:"session_id"`
	Sequence      int            `json:"sequence"`
	TurnID        string         `json:"turn_id"`
	Role          string         `json:"role"`
	Text          string         `json:"text"`
	CreatedAt     string         `json:"created_at"`
	DeliveryState string         `json:"delivery_state"`
	Evidence      []EvidenceRef  `json:"evidence"`
	Extensions    map[string]any `json:"extensions"`
}

type ConversationState struct {
	SchemaVersion       int              `json:"schema_version"`
	ID                  string           `json:"id"`
	Revision            int              `json:"revision"`
	ThroughSequence     int              `json:"through_sequence"`
	SummaryFromSequence int              `json:"summary_from_sequence"`
	Summary             string           `json:"summary"`
	RecentEventIDs      []string         `json:"recent_event_ids"`
	FocusEntityIDs      []string         `json:"focus_entity_ids"`
	PendingQuestions    []map[string]any `json:"pending_questions"`
	CommitmentItemIDs   []string         `json:"commitment_item_ids"`
	Extensions          map[string]any   `json:"extensions"`
}

type Criterion struct {
	ID             string         `json:"id"`
	Kind           string         `json:"kind"`
	Expected       map[string]any `json:"expected"`
	EvidencePolicy string         `json:"evidence_policy"`
}

type Task struct {
	SchemaVersion    int            `json:"schema_version"`
	ID               string         `json:"id"`
	Revision         int            `json:"revision"`
	RootID           string         `json:"root_id"`
	ItemID           *string        `json:"item_id"`
	JobID            *string        `json:"job_id"`
	OccurrenceKey    *string        `json:"occurrence_key"`
	Goal             string         `json:"goal"`
	State            string         `json:"state"`
	Criteria         []Criterion    `json:"criteria"`
	CriterionHash    string         `json:"criterion_hash"`
	CancelGeneration int            `json:"cancel_generation"`
	DeadlineAt       *string        `json:"deadline_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	Extensions       map[string]any `json:"extensions"`
	ParentRootID     *string        `json:"parent_root_id"`
}

type Command struct {
	SchemaVersion     int            `json:"schema_version"`
	OperationKey      string         `json:"operation_key"`
	Capability        string         `json:"capability"`
	CapabilityVersion int            `json:"capability_version"`
	Arguments         map[string]any `json:"arguments"`
	ExpectedRevisions []ReadRef      `json:"expected_revisions"`
	Extensions        map[string]any `json:"extensions"`
}

type Schedule struct {
	Kind         string          `json:"kind"`
	At           *string         `json:"at"`
	AnchorAt     *string         `json:"anchor_at"`
	EverySeconds *int            `json:"every_seconds"`
	LocalTime    *string         `json:"local_time"`
	Timezone     string          `json:"timezone"`
	Weekdays     []int           `json:"weekdays"`
	EventType    *string         `json:"event_type"`
	Filter       *map[string]any `json:"filter"`
	AfterSeq     *int            `json:"after_seq"`
}

type ScheduledJob struct {
	SchemaVersion int            `json:"schema_version"`
	ID            string         `json:"id"`
	Revision      int            `json:"revision"`
	RootID        string         `json:"root_id"`
	Enabled       bool           `json:"enabled"`
	Schedule      Schedule       `json:"schedule"`
	Command       Command        `json:"command"`
	TaskTemplate  map[string]any `json:"task_template"`
	NextDueAt     *string        `json:"next_due_at"`
	Misfire       string         `json:"misfire"`
	GraceSeconds  int            `json:"grace_seconds"`
	Overlap       string         `json:"overlap"`
	MaxAttempts   int            `json:"max_attempts"`
	UpdatedAt     string         `json:"updated_at"`
	Extensions    map[string]any `json:"extensions"`
}

type ActionProposal struct {
	OperationKey string         `json:"operation_key"`
	Kind         string         `json:"kind"`
	Payload      map[string]any `json:"payload"`
}

type Control struct {
	Kind    string         `json:"kind"`
	TaskID  *string        `json:"task_id"`
	Payload map[string]any `json:"payload"`
}

type DecisionEnvelope struct {
	SchemaVersion int              `json:"schema_version"`
	ContextID     string           `json:"context_id"`
	Reply         map[string]any   `json:"reply"`
	Actions       []ActionProposal `json:"actions"`
	Controls      []Control        `json:"controls"`
	Extensions    map[string]any   `json:"extensions"`
}

type ContextManifest struct {
	SchemaVersion    int              `json:"schema_version"`
	ID               string           `json:"id"`
	IntentID         string           `json:"intent_id"`
	SnapshotSeq      int              `json:"snapshot_seq"`
	AsOf             string           `json:"as_of"`
	ReadSet          []ReadRef        `json:"read_set"`
	RequestHash      string           `json:"request_hash"`
	PolicyRevision   int              `json:"policy_revision"`
	OutputSchemaID   string           `json:"output_schema_id"`
	OutputSchemaHash string           `json:"output_schema_hash"`
	ModelProfile     string           `json:"model_profile"`
	InputBytes       int              `json:"input_bytes"`
	InputTokens      int              `json:"input_tokens"`
	TokenCountMode   string           `json:"token_count_mode"`
	Sections         []map[string]any `json:"sections"`
	Extensions       map[string]any   `json:"extensions"`
}

type Context struct {
	SchemaVersion       int                 `json:"schema_version"`
	SystemRules         string              `json:"system_rules"`
	CurrentInput        InputEnvelope       `json:"current_input"`
	World               WorldModelInput     `json:"world"`
	Live                LiveWorldStateInput `json:"live"`
	Consciousness       *ConsciousnessState `json:"consciousness"`
	Conversation        ConversationState   `json:"conversation"`
	RecentEvents        []ConversationEvent `json:"recent_events"`
	Tasks               []Task              `json:"tasks"`
	DeltaEvents         []ChangeEvent       `json:"delta_events"`
	RetrievedEvidence   []EvidenceRef       `json:"retrieved_evidence"`
	CapabilityIDs       []string            `json:"capability_ids"`
	OutputContract      map[string]any      `json:"output_contract"`
	Extensions          map[string]any      `json:"extensions"`
	ContextID           string              `json:"context_id"`
	AsOf                string              `json:"as_of"`
	SnapshotSeq         int                 `json:"snapshot_seq"`
	Sections            []ContextSection    `json:"sections"`
	StaleRefs           []ReadRef           `json:"stale_refs,omitempty"`
	RegisteredEntityIDs []string            `json:"registered_entity_ids,omitempty"`
}

type AuthorizationGrant struct {
	SchemaVersion  int            `json:"schema_version"`
	ID             string         `json:"id"`
	PrincipalID    string         `json:"principal_id"`
	Revision       int            `json:"revision"`
	CapabilityIDs  []string       `json:"capability_ids"`
	Scope          map[string]any `json:"scope"`
	PolicyRevision int            `json:"policy_revision"`
	ExpiresAt      string         `json:"expires_at"`
	Revoked        bool           `json:"revoked"`
	Extensions     map[string]any `json:"extensions"`
}

type ExecutionPermit struct {
	SchemaVersion    int            `json:"schema_version"`
	ID               string         `json:"id"`
	RunID            string         `json:"run_id"`
	GrantID          string         `json:"grant_id"`
	GrantRevision    int            `json:"grant_revision"`
	FencingToken     int            `json:"fencing_token"`
	CancelGeneration int            `json:"cancel_generation"`
	Capability       string         `json:"capability"`
	ProposalHash     *string        `json:"proposal_hash"`
	ExpiresAt        string         `json:"expires_at"`
	ConsumedAt       *string        `json:"consumed_at"`
	Extensions       map[string]any `json:"extensions"`
}

type JobRun struct {
	SchemaVersion          int            `json:"schema_version"`
	ID                     string         `json:"id"`
	TaskID                 string         `json:"task_id"`
	JobID                  *string        `json:"job_id"`
	JobRevision            *int           `json:"job_revision"`
	OccurrenceKey          string         `json:"occurrence_key"`
	ScheduledFor           string         `json:"scheduled_for"`
	State                  string         `json:"state"`
	AttemptNo              int            `json:"attempt_no"`
	FencingToken           int            `json:"fencing_token"`
	LeaseOwner             *string        `json:"lease_owner"`
	LeaseUntil             *string        `json:"lease_until"`
	ExternalIdempotencyKey string         `json:"external_idempotency_key"`
	Command                Command        `json:"command"`
	UpdatedAt              string         `json:"updated_at"`
	Extensions             map[string]any `json:"extensions"`
}

type ExecutorReceipt struct {
	SchemaVersion       int            `json:"schema_version"`
	ID                  string         `json:"id"`
	RunID               string         `json:"run_id"`
	AttemptNo           int            `json:"attempt_no"`
	FencingToken        int            `json:"fencing_token"`
	ReceiptKey          string         `json:"receipt_key"`
	Status              string         `json:"status"`
	ExternalOperationID *string        `json:"external_operation_id"`
	Artifacts           []ObjectRef    `json:"artifacts"`
	Evidence            []EvidenceRef  `json:"evidence"`
	ErrorCode           *string        `json:"error_code"`
	EffectObserved      bool           `json:"effect_observed"`
	ReceivedAt          string         `json:"received_at"`
	Extensions          map[string]any `json:"extensions"`
}

type Verification struct {
	SchemaVersion   int              `json:"schema_version"`
	ID              string           `json:"id"`
	TaskID          string           `json:"task_id"`
	CriterionHash   string           `json:"criterion_hash"`
	Results         []map[string]any `json:"results"`
	VerifierVersion string           `json:"verifier_version"`
	CreatedAt       string           `json:"created_at"`
	Extensions      map[string]any   `json:"extensions"`
}

type WaitSubscription struct {
	SchemaVersion int            `json:"schema_version"`
	ID            string         `json:"id"`
	TaskID        string         `json:"task_id"`
	Generation    int            `json:"generation"`
	EventType     string         `json:"event_type"`
	EntityID      string         `json:"entity_id"`
	ExpectedState string         `json:"expected_state"`
	CursorSeq     int            `json:"cursor_seq"`
	DeadlineAt    string         `json:"deadline_at"`
	State         string         `json:"state"`
	Extensions    map[string]any `json:"extensions"`
}

type ChangeEvent struct {
	SchemaVersion  int            `json:"schema_version"`
	ID             string         `json:"id"`
	Seq            int            `json:"seq"`
	RootID         string         `json:"root_id"`
	EntityType     string         `json:"entity_type"`
	EntityID       string         `json:"entity_id"`
	EntityRevision int            `json:"entity_revision"`
	EventType      string         `json:"event_type"`
	CausationID    *string        `json:"causation_id"`
	Origin         string         `json:"origin"`
	CreatedAt      string         `json:"created_at"`
	Change         map[string]any `json:"change"`
	Extensions     map[string]any `json:"extensions"`
}

type RootBudget struct {
	SchemaVersion    int            `json:"schema_version"`
	RootID           string         `json:"root_id"`
	Revision         int            `json:"revision"`
	ModelCallsUsed   int            `json:"model_calls_used"`
	RetrievalsUsed   int            `json:"retrievals_used"`
	ActionsUsed      int            `json:"actions_used"`
	ReplansUsed      int            `json:"replans_used"`
	OutputTokensUsed int            `json:"output_tokens_used"`
	ActiveMsUsed     int            `json:"active_ms_used"`
	Limits           map[string]any `json:"limits"`
	CooldownUntil    *string        `json:"cooldown_until"`
	Extensions       map[string]any `json:"extensions"`
}

type ConsciousnessDraft struct {
	SchemaVersion    int            `json:"schema_version"`
	FocalGoals       []FocusEntry   `json:"focal_goals"`
	PriorityItems    []FocusEntry   `json:"priority_items"`
	OpenLoops        []FocusEntry   `json:"open_loops"`
	ImportantChanges []FocusEntry   `json:"important_changes"`
	Uncertainties    []string       `json:"uncertainties"`
	BriefSummary     string         `json:"brief_summary"`
	Extensions       map[string]any `json:"extensions"`
}

type ConversationSummaryDraft struct {
	SchemaVersion      int            `json:"schema_version"`
	Summary            string         `json:"summary"`
	FocusEntityIDs     []string       `json:"focus_entity_ids"`
	PendingQuestionIDs []string       `json:"pending_question_ids"`
	CommitmentItemIDs  []string       `json:"commitment_item_ids"`
	Extensions         map[string]any `json:"extensions"`
}

type RequestReceipt struct {
	SchemaVersion int            `json:"schema_version"`
	PrincipalID   string         `json:"principal_id"`
	RequestID     string         `json:"request_id"`
	PayloadHash   string         `json:"payload_hash"`
	IntentID      string         `json:"intent_id"`
	State         string         `json:"state"`
	Response      map[string]any `json:"response"`
	CreatedAt     string         `json:"created_at"`
	Extensions    map[string]any `json:"extensions"`
}

type InputTurn struct {
	SchemaVersion          int             `json:"schema_version"`
	ID                     string          `json:"id"`
	SessionID              string          `json:"session_id"`
	PrincipalID            string          `json:"principal_id"`
	RequestID              string          `json:"request_id"`
	IntentID               string          `json:"intent_id"`
	State                  string          `json:"state"`
	Input                  InputEnvelope   `json:"input"`
	Reply                  *map[string]any `json:"reply"`
	CommittedOperationKeys []string        `json:"committed_operation_keys"`
	ProcessingOwner        *string         `json:"processing_owner"`
	LeaseUntil             *string         `json:"lease_until"`
	UpdatedAt              string          `json:"updated_at"`
	Extensions             map[string]any  `json:"extensions"`
}

type ExecutionAttempt struct {
	SchemaVersion int            `json:"schema_version"`
	RunID         string         `json:"run_id"`
	AttemptNo     int            `json:"attempt_no"`
	FencingToken  int            `json:"fencing_token"`
	DispatchState string         `json:"dispatch_state"`
	PreparedAt    string         `json:"prepared_at"`
	DispatchedAt  *string        `json:"dispatched_at"`
	FinishedAt    *string        `json:"finished_at"`
	ExecutorID    string         `json:"executor_id"`
	CommandHash   string         `json:"command_hash"`
	LastError     *string        `json:"last_error"`
	Extensions    map[string]any `json:"extensions"`
}

type ConsumerCursor struct {
	SchemaVersion int            `json:"schema_version"`
	ConsumerID    string         `json:"consumer_id"`
	LastSeq       int            `json:"last_seq"`
	Revision      int            `json:"revision"`
	Extensions    map[string]any `json:"extensions"`
}

type RuleState struct {
	SchemaVersion   int            `json:"schema_version"`
	RuleID          string         `json:"rule_id"`
	RootID          string         `json:"root_id"`
	CursorSeq       int            `json:"cursor_seq"`
	NextAllowedAt   *string        `json:"next_allowed_at"`
	NoProgressCount int            `json:"no_progress_count"`
	LastEffectHash  *string        `json:"last_effect_hash"`
	Extensions      map[string]any `json:"extensions"`
}

type AlarmSession struct {
	SchemaVersion  int             `json:"schema_version"`
	ID             string          `json:"id"`
	RunID          string          `json:"run_id"`
	Revision       int             `json:"revision"`
	State          string          `json:"state"`
	DeviceID       string          `json:"device_id"`
	AudioRef       ObjectRef       `json:"audio_ref"`
	PlaybackHandle *string         `json:"playback_handle"`
	SavedSettings  *map[string]any `json:"saved_settings"`
	StartedAt      *string         `json:"started_at"`
	StoppedAt      *string         `json:"stopped_at"`
	StopReason     *string         `json:"stop_reason"`
	Extensions     map[string]any  `json:"extensions"`
}

type Notification struct {
	SchemaVersion   int            `json:"schema_version"`
	ID              string         `json:"id"`
	RunID           *string        `json:"run_id"`
	NotificationKey string         `json:"notification_key"`
	State           string         `json:"state"`
	Text            string         `json:"text"`
	CreatedAt       string         `json:"created_at"`
	DeliveredAt     *string        `json:"delivered_at"`
	AcknowledgedAt  *string        `json:"acknowledged_at"`
	Extensions      map[string]any `json:"extensions"`
}

type CapabilityDescriptor struct {
	SchemaVersion       int            `json:"schema_version"`
	ID                  string         `json:"id"`
	Version             int            `json:"version"`
	ArgumentsSchema     map[string]any `json:"arguments_schema"`
	ResultSchema        map[string]any `json:"result_schema"`
	SideEffectClass     string         `json:"side_effect_class"`
	SupportsIdempotency bool           `json:"supports_idempotency"`
	SupportsQuery       bool           `json:"supports_query"`
	SupportsCancel      bool           `json:"supports_cancel"`
	TimeoutMs           int            `json:"timeout_ms"`
	Extensions          map[string]any `json:"extensions"`
}

type ModelCallRecord struct {
	SchemaVersion   int            `json:"schema_version"`
	CallID          string         `json:"call_id"`
	RootID          string         `json:"root_id"`
	ContextID       string         `json:"context_id"`
	ProviderProfile string         `json:"provider_profile"`
	ModelID         string         `json:"model_id"`
	RequestHash     string         `json:"request_hash"`
	OutputRef       *ObjectRef     `json:"output_ref"`
	StartedAt       string         `json:"started_at"`
	FinishedAt      *string        `json:"finished_at"`
	InputTokens     int            `json:"input_tokens"`
	OutputTokens    int            `json:"output_tokens"`
	CountMode       string         `json:"count_mode"`
	Status          string         `json:"status"`
	ErrorCode       *string        `json:"error_code"`
	Extensions      map[string]any `json:"extensions"`
}

type FixtureItemValue struct {
	Title  string  `json:"title"`
	Domain string  `json:"domain"`
	DueAt  *string `json:"due_at"`
	Status string  `json:"status"`
}

type DeviceAvailabilityValue struct {
	Available bool   `json:"available"`
	DeviceID  string `json:"device_id"`
}

type SourceHealthValue struct {
	SourceID  string `json:"source_id"`
	Reachable bool   `json:"reachable"`
}

type MasterPreferenceValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type ProjectBackgroundValue struct {
	ProjectID string `json:"project_id"`
	Text      string `json:"text"`
}

type EntityRelationValue struct {
	Relation       string `json:"relation"`
	TargetEntityID string `json:"target_entity_id"`
}

type CoreWork struct {
	SchemaVersion int              `json:"schema_version"`
	RunID         string           `json:"run_id"`
	AttemptNo     int              `json:"attempt_no"`
	FencingToken  int              `json:"fencing_token"`
	CommandHash   string           `json:"command_hash"`
	State         string           `json:"state"`
	Receipt       *ExecutorReceipt `json:"receipt"`
	Checkpoint    *map[string]any  `json:"checkpoint"`
	UpdatedAt     string           `json:"updated_at"`
	Extensions    map[string]any   `json:"extensions"`
}

type ContextSection struct {
	Name          string `json:"name"`
	SelectedCount int    `json:"selected_count"`
	OmittedCount  int    `json:"omitted_count"`
	Bytes         int    `json:"bytes"`
	Reason        string `json:"reason"`
}
