"""Generate DTOs from authoritative schema; run from repository root."""
import json,pathlib
root=pathlib.Path(__file__).resolve().parents[2]
s=json.loads((root/'docs/contracts.schema.json').read_text())
(root/'src/contract/contracts.schema.json').write_text(json.dumps(s,indent=2,ensure_ascii=False)+'\n')
def name(k):
 return ''.join({'id':'ID','ids':'IDs','sha256':'SHA256','json':'JSON','url':'URL','utc':'UTC'}.get(p,p.capitalize()) for p in k.split('_'))
def typ(p):
 if '$ref' in p:return p['$ref'].split('/')[-1]
 if 'const' in p:return 'int' if isinstance(p['const'],int) else 'string'
 if 'anyOf' in p:
  q=[x for x in p['anyOf'] if x.get('type')!='null']
  return '*'+typ(q[0]) if len(q)==1 and len(q)!=len(p['anyOf']) else 'any'
 t=p.get('type')
 if isinstance(t,list):return 'any'
 if t=='array':return '[]'+typ(p.get('items',{}))
 return {'string':'string','integer':'int','number':'float64','boolean':'bool','object':'map[string]any'}.get(t,'any')
out=['// Code generated by contract/generate.py; DO NOT EDIT.','package contract','']
for n,d in s['$defs'].items():
 if d.get('type')=='object' and d.get('properties'):
  out+=['type '+n+' struct {']
  for k,p in d['properties'].items():out+=[' '+name(k)+' '+typ(p)+' `json:"'+k+('' if k in d.get('required',[]) else ',omitempty')+'"`']
  out+=['}','']
 else:out+=['type '+n+' '+typ(d),'']
(root/'src/contract/dto_generated.go').write_text('\n'.join(out))

import subprocess
subprocess.run(["gofmt", "-w", str(root/"src/contract/dto_generated.go")], check=True)
